[formatter.clang-format]
command = "clang-format"
options = ["-i"]
includes = ["*.cpp", "*.h", "*.ino"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.json", "*.md", "*.yml", "*.yaml"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.python]
command = "black"
includes = ["*.py"]

[formatter.shfmt]
command = "shfmt"
options = ["-i", "2", "-w"]
includes = ["*.sh"]
